name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Commit
        uses: actions/checkout@v3
      -
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
      -
        run: |
          npm ci
      -
        name: Run build
        run: |
          npm run build